### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by vdKolk** [coreos/manifest#56] opened 2015-02-13 10:16 UTC
I'm using coreOS on a VMware basis, with a configdrive iso
With the new 591.0.0 alpha release, the user-configdrive fails. I'm using a YML structure and it's being listed as a .json file.

```
CoreOS alpha (591.0.0)
Failed Units: 1
  user-configdrive.service
core@slcoreos01 ~ $ systemctl status user-configdrive.service 
● user-configdrive.service - Load cloud-config from /media/configdrive
   Loaded: loaded (/usr/lib64/systemd/system/user-configdrive.service; static; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2015-02-13 09:48:20 UTC; 14min ago
  Process: 507 ExecStart=/usr/bin/coreos-cloudinit --from-configdrive=/media/configdrive (code=exited, status=1/FAILURE)
 Main PID: 507 (code=exited, status=1/FAILURE)

Feb 13 09:48:20 slcoreos01 coreos-cloudinit[507]: Checking availability of "cloud-drive"
Feb 13 09:48:20 slcoreos01 coreos-cloudinit[507]: Fetching user-data from datasource of type "cloud-drive"
Feb 13 09:48:20 slcoreos01 coreos-cloudinit[507]: Attempting to read from "/media/configdrive/openstack/latest/user_data"
Feb 13 09:48:20 slcoreos01 coreos-cloudinit[507]: Fetching meta-data from datasource of type "cloud-drive"
Feb 13 09:48:20 slcoreos01 coreos-cloudinit[507]: Attempting to read from "/media/configdrive/openstack/latest/meta_data.json"
Feb 13 09:48:20 slcoreos01 coreos-cloudinit[507]: Failed fetching meta-data from datasource: unexpected end of JSON input
Feb 13 09:48:20 slcoreos01 systemd[1]: user-configdrive.service: main process exited, code=exited, status=1/FAILURE
Feb 13 09:48:20 slcoreos01 systemd[1]: Failed to start Load cloud-config from /media/configdrive.
Feb 13 09:48:20 slcoreos01 systemd[1]: Unit user-configdrive.service entered failed state.
Feb 13 09:48:20 slcoreos01 systemd[1]: user-configdrive.service failed.
```

**Comment by gwiersma** [comment] 2015-02-13 10:27
I am experiencing the same problem! Also running on Alpha 591.0.0 on VMWare.

**Comment by crawford** [comment] 2015-02-13 17:22
This looks like a bug in coreos-cloudinit. I'll dig into it and follow up.

**Comment by crawford** [comment] 2015-02-13 18:21
Yep, it's a regression in cloudinit. It will be fixed in the next release.

**Closed by crawford** 2015-02-13 18:21 UTC
